import type { Product } from '@/lib/products'

export type Category = { slug: string; label: string; eyebrow: string; title: string; description: string; image: string; items: string[]; tone: string }

export const categories: Category[] = [
  { slug: 'news', label: 'News', eyebrow: 'The latest edit', title: 'What is worth knowing now.', description: 'New launches, cultural shifts, and considered finds from the worlds shaping how we live.', image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1400&q=85', items: ['Celebrity', 'New launches', 'Treatment & FDA news', 'Industry & retail news'], tone: 'bg-secondary' },
  { slug: 'face', label: 'Face', eyebrow: 'The face edit', title: 'Care for the skin you are in.', description: 'Thoughtful routines and proven essentials for every complexion, concern, and daily ritual.', image: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=1400&q=85', items: ['Acne', 'Anti-aging', 'Eye care', 'Hyperpigmentation', 'Makeup', 'Sensitive skin', 'Skin care', 'Skin conditions', 'Smile', 'Sun care'], tone: 'bg-accent/10' },
  { slug: 'treatments', label: 'Treatments', eyebrow: 'The treatment edit', title: 'Research before the ritual.', description: 'A clearer way to understand treatments, devices, ingredients, and what comes next.', image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1400&q=85', items: ['Neurotoxins', 'Fillers', 'Lasers & energy devices', 'Microneedling', 'Post-procedure skin care', 'Regenerative aesthetics', 'Skin lifting and tightening'], tone: 'bg-primary/10' },
  { slug: 'body', label: 'Body', eyebrow: 'The body edit', title: 'Good care, from head to toe.', description: 'The products and practices that make everyday body care feel more intentional.', image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1400&q=85', items: ['Skin care', 'Body sculpting', 'Breasts', 'Butts', 'Cellulite', 'Fragrance', 'Hands + nails', 'Legs', 'Pregnancy'], tone: 'bg-secondary' },
  { slug: 'hair', label: 'Hair', eyebrow: 'The hair edit', title: 'A better hair day starts here.', description: 'Useful guidance for healthier hair, calmer scalps, and routines that fit real life.', image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1400&q=85', items: ['Bond repair', 'Celebrity hair', 'Dry hair', 'Frizzy hair', 'Gray hair', 'Hair color', 'Hair growth', 'Hair repair', 'Scalp health', 'Tips + tutorials'], tone: 'bg-accent/10' },
  { slug: 'awards', label: 'Awards', eyebrow: 'The Commonly awards', title: 'The things we would buy again.', description: 'Our highest-conviction picks, recognized for doing one thing exceptionally well.', image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=1400&q=85', items: ['Best in class', 'Editor favorites', 'Reader favorites', 'New and notable'], tone: 'bg-primary/10' },
  { slug: 'shopping', label: 'Shopping', eyebrow: 'The shopping edit', title: 'Buy less. Choose better.', description: 'A focused collection of products selected for usefulness, longevity, and quiet delight.', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1400&q=85', items: ['Best sellers', 'Under $25', 'Gifts', 'Everyday essentials'], tone: 'bg-secondary' },
  { slug: 'creams', label: 'Creams', eyebrow: 'The cream edit', title: 'The right cream changes everything.', description: 'From rich body butters to featherlight face creams, discover textures made for every ritual and skin need.', image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1400&q=85', items: ['Face creams', 'Moisturizers', 'Body creams', 'Night creams', 'Hand creams', 'Natural creams'], tone: 'bg-accent/10' },
]

export function getCategory(slug: string) { return categories.find((category) => category.slug === slug) }
export function getCategoryProducts(category: Category, products: Product[]) { return products.filter((product) => product.category.toLowerCase() === category.label.toLowerCase()).slice(0, 6) }
