'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, ArrowRight, Check } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

export default function RegisterPage() {
  const [submitted, setSubmitted] = useState(false)
  return <main className="grid min-h-screen lg:grid-cols-2"><div className="hidden bg-primary p-10 text-primary-foreground lg:flex lg:flex-col lg:justify-between"><Link href="/" className="font-serif text-2xl">Commonly.</Link><div><p className="text-xs uppercase tracking-[0.2em] text-primary-foreground/60">Join the common room</p><h1 className="mt-4 max-w-md font-serif text-6xl leading-[.95]">Good things are better shared.</h1><p className="mt-6 max-w-sm leading-7 text-primary-foreground/70">Save your favorite finds, follow thoughtful guides, and get the occasional note from us.</p></div><p className="text-sm text-primary-foreground/50">© 2026 Commonly.</p></div><div className="flex flex-col p-6 sm:p-10 lg:justify-center lg:px-20"><Link href="/" className="mb-16 flex items-center gap-2 text-sm lg:mb-20"><ArrowLeft className="size-4" /> Back home</Link><div className="max-w-md"><p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Create your account</p><h2 className="mt-3 font-serif text-4xl">Make yourself at home.</h2>{submitted ? <div className="mt-8 border border-border bg-secondary p-6"><div className="grid size-10 place-items-center rounded-full bg-primary text-primary-foreground"><Check className="size-5" /></div><h3 className="mt-5 font-serif text-2xl">You&apos;re in.</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Your account is ready. We&apos;ll keep the good stuff coming.</p><Link href="/" className="mt-6 inline-flex h-8 items-center justify-center rounded-lg bg-primary px-2.5 text-sm font-medium text-primary-foreground transition-all hover:bg-primary/80 focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50">Explore the collection</Link></div> : <form onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }} className="mt-8 flex flex-col gap-5"><div className="flex flex-col gap-2"><Label htmlFor="name">Full name</Label><Input id="name" required placeholder="Alex Morgan" /></div><div className="flex flex-col gap-2"><Label htmlFor="email">Email address</Label><Input id="email" type="email" required placeholder="alex@example.com" /></div><div className="flex flex-col gap-2"><Label htmlFor="password">Password</Label><Input id="password" type="password" required minLength={8} placeholder="8+ characters" /></div><Button type="submit" size="lg" className="mt-3">Create account <ArrowRight data-icon="inline-end" /></Button><p className="text-center text-xs text-muted-foreground">By joining, you agree to our terms and privacy policy.</p></form>}<p className="mt-8 text-sm text-muted-foreground">Already a member? <Link href="/" className="text-foreground underline underline-offset-4">Sign in</Link></p></div></div></main>
}

